version: "3.9"

volumes:
  opensearch: {}
  data: {}

services:
  opensearch:
    image: opensearchproject/opensearch:1
    env_file:
      - prod.opensearch.env
    volumes:
      - opensearch:/usr/share/opensearch/data

  opencast:
    image: lbtu-opencast:latest
    env_file:
      - prod.opencast.env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data